config/routes.rb
Venturechallenge::Application.routes.draw do
  get "users/new"
  get "users/create"
  
  get 'welcome' => 'home#welcome'
  get 'adminpanel' => 'home#admin'
  get 'leaderboards' => 'home#leaderboards'
  post 'leaderboards' => 'home#leaderboards'

  get 'logout' => 'sessions#destroy'
  post 'assign_league' => 'leagues#assign_league'
  get 'quit_league' => 'leagues#quit_league'

  get 'fakebadge' => 'home#fakebadges'

  post 'webhooks/orders/create' => 'webhooks#order_new'
  post 'webhooks/customers/create' => 'webhooks#customers_new'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'auth/shopify/callback' => :authorize
    get 'auth/linkedin/callback' => :admin_authorize
    get 'admin_login' => :admin_new
    post 'admin_login' => :admin_create
  end
  root :to => 'home#index'

  resources :users, :only => [:new, :create]
  resources :leagues
  resources :teamstats
  resources :posts

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # at all points inside the app, ensure the user is logged in
  # redirect to the login screen if not

  before_filter :ensure_logged_in

  #index is a triage that sends user to either the admin or student section depending on session params

  def index
    redirect_to after_sign_in_path 
  end

  #admin is the admin control panel, which lists all leagues owned by the admin user

  def admin
    @leagues = League.where("admin_id = '#{current_user.id}'")
  end

  #leaderboards is the default view for students
  # in admin view, user can select which league to view via dropdown

  def is_student
    session[:shopify]
  end

  def is_teacher
    session[:linkedin]
  end

  def leaderboards
    # first determine if user is admin or student
    # populate @league and @amind_leagues as necessary
    if is_student
      redirect_to leagues_path unless current_store.league_id # help me pick a league if I don't have one
      @league = League.find(current_store.league_id)
    elsif is_teacher
      @admin_leagues = League.where("admin_id = #{current_user.id}")
      if params[:league]
        @league = League.find(params[:league])
      else  
        @league = League.find_by(admin_id: current_user.id)
      end
    end
    
    @stores = @league.cached_stores
    @orders = @league.cached_orders
    @countdown = league_countdown

    # the gon. variables are used to pass data to javascript for charts
    gon.numberofTeams = @stores.count

    initialize_point_winners
    initialize_pointschart unless @orders.count == 0 
  end


  private


  #triages users to the appropriate login
  def after_sign_in_path
     if session[:shopify]
       return leagues_path unless current_store.league_id
       return leaderboards_path
     elsif session[:linkedin]
       return adminpanel_path
     end
  end

  #creates a string with the time remainnig in the league, or returns game over
  def league_countdown
    return "Game Over!" if Time.now > @league.end_date

    t = @league.end_date - Time.now

    mm, ss = t.divmod(60)
    hh, mm = mm.divmod(60)
    dd, hh = hh.divmod(24)
    "%d days, %d hours, %d minutes and %d seconds" % [dd, hh, mm, ss]
  end
  
  def initialize_point_winners
    #figure out daily and weekly winners, [this should probably be a delay job]
    @pointsyesterday = 0
    @pointsthisweek = 0
    @stores.each do |store|
      ptsystrdy = store.points.where(created_at: (Time.now.midnight - 1.day)..Time.now.midnight).map(&:value).sum
      if ptsystrdy > @pointsyesterday
        @pointsyesterday = ptsystrdy
        @yesterdaypointswinner = User.find(store.user_id).name
      end

      ptswk = store.points.where(created_at: (Time.now - 7.day)..Time.now).map(&:value).sum
      if ptswk > @pointsthisweek
        @pointsthisweek = ptswk
        @thisweekpointswinner = User.find(store.user_id).name
      end
    end
  end

  # sets up data for charts and assigns .gon variables to be passed to js
  def initialize_pointschart

    # array for colors
    gon.color = [] 

    # determine time range of game
    oldestordertime = @orders.maximum("created_at")
    timerange = oldestordertime - @league.start_date

    #set number of time chunks
    if timerange > (86400*13)
      timechunks = 13
    else
      timechunks = timerange / 86400
      timechunks = timechunks.to_i
    end
    
    # setup time range 
    timeinterval = (timerange / timechunks) + 60
    chartlabelarray = [@league.start_date]
    
    #setup label array
    i = 1
    timechunks.times do
      chartlabelarray << (@league.start_date+(timeinterval * i))
      i += 1
    end

    #initialize array data
    gon.data = []

    #scales the opacity of the colored fills depending on the number of players
    opac = 1/(@stores.count).to_f

    #
    @stores.each do |store|
      aggregatepoints = [0]
      i = 1
      (timechunks).times do 
        puts 
        timechunkpoints = store.points.select { |p| p.created_at.between?(chartlabelarray[0],chartlabelarray[i]) }
        aggregatepoints << timechunkpoints.map(&:value).sum
        i += 1
      end
      #generate random color and push into color array
      r = rand(255)
      g = rand(255)
      b = rand(255)
      linecolor = "rgba(#{r},#{g},#{b},1)"
      fillcolor = "rgba(#{r},#{g},#{b},#{opac})"
      gon.data << { 
        "name" => "#{User.find(store.user_id).name}", 
        "linecolor" => linecolor, 
        "fillcolor" => fillcolor,
        "points" => aggregatepoints, 
        "ident" => "store#{store.id}", 
        "totalpts" => Point.where("store_id = #{store.id}").sum(:value)
        }
    end

    #format label array and pass to .gon
    chartlabelarray.map!{|x| x.strftime("%m / %d") }
    gon.labels = chartlabelarray

  end

end

app/helpers/home_helper.rb
module HomeHelper

  def customer_name(order)
    name = ''
    name += [order.customer.first_name, order.customer.last_name].join(" ") if order.respond_to?(:customer)
    name.strip
  end

end

app/views/home/admin.html.erb
<div class = "large-9 large-centered small-12 columns">
	<h1> Your Leagues </h1>

	<h6>Create, Edit or Delete your leagues</h6>
	<br/>

	<% if @leagues %>
		<table>
			<tr>
				<td></td>
				<td>Name</td>
				<td>School</td>
				<td>Start</td>
				<td>End</td>
				<td>Status</td>
				<td>Teams</td>
			</tr>
		<% @leagues.each do |league| %>
			<tr>
				<td><%= link_to "Edit", edit_league_path(league.id) %></td>
				<td><%= link_to league.name, "/leaderboards?league=#{league.id}" %></td>
				<td><%= league.school %></td>
				<td><%= time_tag league.start_date %></td>
				<td><%= time_tag league.end_date %></td>
				<td><% if Time.now < league.end_date %>
							<%= distance_of_time_in_words(Time.now, league.end_date) %> Remaining
						<% else %>
							Complete
						<% end  %></td>
				<td align="center"><%= Store.where("league_id = #{league.id}").count %></td>
			</tr>
		<% end  %>
			<td align="center"><a href="<%= new_league_path %>">
	        <i class="fa fa-plus-square-o fa-lg"></i>
	        </a>
	    </td>
			<td><a href="<%= new_league_path %>">
	        <span class="menu_a"> Add New League</span>
	        </a>
	     </td>
		</table>
	<% end  %>
</div>

app/views/home/index.html.erb
redirect only

app/views/home/leaderboards.html.erb
<div class ="row" id="leaderboard">
    <div  class = "large-12 large-centered columns">
        <div class = "leaderboard">

<div class = "row">

    <div class = "large-6 columns">
        <div class="paneltop">
            <div class="league-info">
                    <% if session[:linkedin] && @admin_leagues.count > 1 %>
                    <!-- admin-view league select -->
                    <a href="#" data-dropdown="drop1"><h5><%= @league.name %> <i class="fa fa-caret-down"></i></h5></a>
                        <ul id="drop1" class="f-dropdown" data-dropdown-content>
                          <% @admin_leagues.each do |league| %>  
                          <li><%= link_to league.name, "/leaderboards?league=#{league.id}" %></li>
                        <% end %>
                        </ul>
                    <% else  %>
                    <h3><%= @league.name%></h3>
                    <% end %>
            </div>
            <div class="py-info">
                <div class="row">
                    <div class="small-9 columns" id="lg">
                        <h6><%= @countdown %> remaining.</h6>
                        <h6>Start: <%= @league.start_date.to_s(:long) %></h6>
                        <h6>End: <%= @league.end_date.to_s(:long) %></h6>  
                    </div>
                    <div class="small-3 columns" id="lg">
                        <%= link_to "Leave league", quit_league_path, class: "button", id: "infobutton" %>
                    </div>
                </div>    
                            
            </div>
        </div>
    </div>

    <div class = "large-3 columns">
        <div class="paneltop">
            <div class="points-yesterday">
                <i class="fa fa-rocket fa-3x"></i>
                <p>Most Points Yesterday</p>
            </div>
            <div class="py-info">
                <div class="row">
                    <div class="small-5 columns">
                        <h4><%= number_with_delimiter(@pointsyesterday) %></h4>
                    </div>
                    <div class="small-7 columns">
                        <h4><%= @yesterdaypointswinner %></h4>
                    </div>
                </div>                
            </div>
        </div>
    </div>

        <div class = "large-3 columns">
        <div class="paneltop">
            <div class="points-week">
                <i class="fa fa-trophy fa-3x"></i>
                <p>7-Day Points Winner</p>
            </div>
            <div class="py-info">
                <div class="row">
                    <div class="small-5 columns">
                        <h4><%= number_with_delimiter(@pointsthisweek) %></h4>
                    </div>
                    <div class="small-7 columns">
                        <h4><%= @thisweekpointswinner %></h4>
                    </div>
                </div>                
            </div>
        </div>
    </div>

</div>
</div>


    <div class="large-12 columns">
        <h3 id="table_title">Current Standings </h3>
            <table id="standings">
              <tr>
                <th>Color</th>
                <th>Store</th>
                <th>Total Revenue</th>
                <th>Orders</th>
                <th>Customers</th>
                <th>Points</th>
                <th>Badges</th>
              </tr>
                <% @stores.each do |store| %>
                    <tr>
                    <td class = "store<%= store.id %>"></td>
                    <td><%= User.find(store.user_id).name %></td>
                    <td><%= number_to_currency(Order.where("store_id = #{store.id}").sum(:subtotal_price)) %></td>
                    <td><%= Order.where("store_id = #{store.id}").count %></td>
                    <td><%= Customer.where("store_id = #{store.id}").count %></td>
                    <td><%= Point.where("store_id = #{store.id}").sum(:value) %></td>
                    <td><% store.badges.reverse[0..4].each do |badge| %>
                            <% if badge.badge_asset %>
                                <%= image_tag badge.badge_asset.url, size: "30x30" %>
                            <% end %>
                        <% end %>
                    </td>
                    </tr>
                <% end %>
            </table>
</div>
<div class="large-6 columns">
            <% if @orders.count > 0  %>
            <div class = "linechart">
                <h4 class="linetitle">Points Over Time</h4>
                <canvas id="LineChart" width="590" height="400"></canvas>
            </div>
</div>
<div class="large-6 columns">
            <div class = "barchart">
                <h4 class="bartitle">Total Points Per Store</h4>
                <canvas id="BarChart" width="590" height="400"></canvas>
            </div>
        <% else %>
            <br/>
            <br/>
            <br/>
            <h4>Not enough data for Charting</h4>
        <% end %>

        </div>
    </div>
</div>